springdoc:
  packagesToScan: com.citihub.configr.namespace, com.citihub.configr.version
  pathsToMatch: /**
mongodb:
  uri: mongodb://localhost:27017/?ssl=false
  db: configr
  auth_db: admin
  username:
  password: