authentication:
  enabled: false
  proxy:
    host:
    port:
cors:
  allowedOrigins: "*"
springdoc:
  packagesToScan: com.citihub.configr.namespace, com.citihub.configr.version
  pathsToMatch: /**
mongodb:
  uri: mongodb://localhost:27017/?ssl=false
  db: configr
  auth_db: admin
  username:
  password:
  mongo_keystore_path:
  mongo_keystore_password:
azure:
  activedirectory:
    client-id: 11111111-1111-1111-1111-1111111111111111
    app-id-uri: <your-app-ID-URI>