name: build-test
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Setup target dir for Contrast
        run: mkdir -p /home/runner/work/configr/configr/target
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots contrast:install verify
        env:
          CONTRAST__API__API_KEY: ${{ secrets.CONTRAST__API__API_KEY }}
          CONTRAST__API__ORGANIZATION_ID: ${{ secrets.CONTRAST__API__ORGANIZATION_ID }}
          CONTRAST__API__SERVICE_KEY: ${{ secrets.CONTRAST__API__SERVICE_KEY }}
          CONTRAST__API__URL: ${{ secrets.CONTRAST__API__URL }}
          CONTRAST__API__USER_NAME: ${{ secrets.CONTRAST__API__USER_NAME }}
          CONTRAST__CI_ENVIRONMENT: ${{ secrets.CONTRAST__CI_ENVIRONMENT }}
      - name: "Codecov upload"
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/jacoco-ut/jacoco.xml
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE="${{ secrets.IMAGE_SIGN_PWD }}"
          DOCKER_CONTENT_TRUST=1 docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/configr:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/configr:${{ github.sha }}